version: '3.1'
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: greenrun_mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greenrun
      USER: 1000

  adminer:
    image: adminer:latest
    hostname: adminer
    container_name: greenrun_adminer
    ports:
      - '8080:8080'
